# Generated by Django 5.2.1 on 2026-02-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("logo", models.ImageField(upload_to="university_logos/")),
                ("description", models.TextField()),
                ("mini_description", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
                "ordering": ["-updated_at"],
            },
        ),
    ]
