# Generated by Django 5.2.1 on 2026-02-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="university_images/"
            ),
        ),
    ]
