# Generated by Django 6.0.2 on 2026-02-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_university_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSlide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard (Quote)"),
                            ("ZOOM", "Zoom (Cards)"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Main title of the slide", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Description or subtitle"),
                ),
                (
                    "bg_image",
                    models.ImageField(
                        help_text="Background image for the slide",
                        upload_to="slider_bg/",
                    ),
                ),
                (
                    "button_text",
                    models.CharField(
                        blank=True,
                        help_text="Button text (Standard layout)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "button_url",
                    models.CharField(
                        blank=True,
                        help_text="Button URL (Standard layout)",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "quote_text",
                    models.TextField(
                        blank=True, help_text="Quote text (Standard layout)", null=True
                    ),
                ),
                (
                    "card_1_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "card_1_date",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Feb 23, 2026 08:00 PM Singapore",
                        max_length=100,
                    ),
                ),
                (
                    "card_1_text",
                    models.TextField(
                        blank=True, help_text="Provider text or description"
                    ),
                ),
                (
                    "card_1_link",
                    models.URLField(
                        blank=True, help_text="Zoom link logic applies here", null=True
                    ),
                ),
                (
                    "card_1_image",
                    models.ImageField(blank=True, null=True, upload_to="slider_cards/"),
                ),
                (
                    "card_2_title",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("card_2_date", models.CharField(blank=True, max_length=100)),
                ("card_2_text", models.TextField(blank=True)),
                ("card_2_link", models.URLField(blank=True, null=True)),
                (
                    "card_2_image",
                    models.ImageField(blank=True, null=True, upload_to="slider_cards/"),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Home Slide",
                "verbose_name_plural": "Home Slides",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="university",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
