# Generated by Django 5.2.1 on 2026-02-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_homeslide_alter_university_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homeslide",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
