# Generated by Django 6.0.2 on 2026-02-15 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_homeslide_id_alter_university_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorySubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for the category tab (e.g., 'business')",
                        unique=True,
                    ),
                ),
                (
                    "svg_icon",
                    models.FileField(
                        help_text="Upload SVG or Image icon",
                        upload_to="category_icons/",
                    ),
                ),
                ("description", models.TextField()),
                ("quote", models.TextField(blank=True)),
                ("author", models.CharField(blank=True, max_length=100)),
                ("link", models.URLField(blank=True, null=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Explore Category",
                "verbose_name_plural": "Explore Categories",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="homeslide",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("provider", models.CharField(default="Starweaver", max_length=200)),
                ("description", models.TextField()),
                ("badge", models.CharField(default="See more", max_length=50)),
                (
                    "gradient",
                    models.CharField(
                        default="linear-gradient(135deg, #a71d78 0%, #d42e68 100%)",
                        help_text="CSS Gradient string",
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional image to override gradient",
                        null=True,
                        upload_to="subject_images/",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="main.categorysubject",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
