# Generated by Django 5.2.1 on 2026-02-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_alter_categorysubject_id_alter_feature_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.CharField(max_length=200),
        ),
    ]
