# Generated by Django 6.0.2 on 2026-02-15 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_categorysubject_id_alter_feature_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="university",
            name="banner_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="university_banners/"
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="certification_type",
            field=models.CharField(default="Professional Certificate", max_length=100),
        ),
        migrations.AddField(
            model_name="university",
            name="course_count",
            field=models.PositiveIntegerField(
                default=4, help_text="Number of courses in the program"
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="duration_weeks",
            field=models.PositiveIntegerField(
                default=32, help_text="Duration in weeks"
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="university",
            name="language",
            field=models.CharField(default="English", max_length=50),
        ),
        migrations.AddField(
            model_name="university",
            name="level",
            field=models.CharField(default="Intermediate", max_length=50),
        ),
        migrations.AddField(
            model_name="university",
            name="months_duration",
            field=models.PositiveIntegerField(
                default=8, help_text="Duration in months"
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="original_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Original price before discount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="pacing",
            field=models.CharField(default="Instructor-paced", max_length=50),
        ),
        migrations.AddField(
            model_name="university",
            name="prerequisites",
            field=models.TextField(default="None"),
        ),
        migrations.AddField(
            model_name="university",
            name="skills_gained",
            field=models.TextField(
                default="",
                help_text="Comma-separated list of skills (e.g., Marketing, Tourism)",
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="university",
            name="student_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of learners enrolled"
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="transcripts",
            field=models.CharField(
                default="English, 中文", help_text="Available transcripts", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="tuition_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current price",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="university",
            name="verified_by",
            field=models.CharField(
                default="HKPolyUx",
                help_text="Entity verifying the course",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="categorysubject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="feature",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="homeslide",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="populartopic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trendingcategory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="trendingtopic",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="university",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.CreateModel(
            name="Instructor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        help_text="Job title or academic position", max_length=200
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="instructors/"),
                ),
                (
                    "institution_logo",
                    models.ImageField(
                        blank=True,
                        help_text="Logo of the instructor's institution",
                        null=True,
                        upload_to="instructor_logos/",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructors",
                        to="main.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                (
                    "user_image",
                    models.ImageField(blank=True, null=True, upload_to="reviewers/"),
                ),
                ("user_location", models.CharField(blank=True, max_length=100)),
                ("quote", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(default=5, help_text="Rating out of 5"),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="main.university",
                    ),
                ),
            ],
        ),
    ]
