# Generated by Django 5.2.1 on 2026-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0015_alter_categorysubject_id_alter_feature_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZoomRegistration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("country", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("zoom_link", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Zoom Registration",
                "verbose_name_plural": "Zoom Registrations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="feature",
            name="icon",
            field=models.CharField(
                choices=[
                    ("fa-book-open", "fa-book-open"),
                    ("fa-user-friends", "fa-user-friends"),
                    ("fa-video", "fa-video"),
                    ("fa-clock", "fa-clock"),
                    ("fa-certificate", "fa-certificate"),
                    ("fa-globe", "fa-globe"),
                ],
                max_length=200,
            ),
        ),
    ]
