# Generated by Django 5.2.1 on 2026-03-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0016_zoomregistration_alter_feature_icon"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="university",
            options={
                "ordering": ["orders", "-updated_at"],
                "verbose_name": "University",
                "verbose_name_plural": "Universities",
            },
        ),
        migrations.AddField(
            model_name="university",
            name="orders",
            field=models.PositiveIntegerField(
                default=0, help_text="Порядок сортировки"
            ),
        ),
    ]
