# Generated by Django 5.2.1 on 2026-03-06 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0017_alter_university_options_university_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessService",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "icon_class",
                    models.CharField(
                        default="fas fa-book",
                        help_text="FontAwesome icon class (e.g., 'fas fa-book')",
                        max_length=50,
                    ),
                ),
                (
                    "color_class",
                    models.CharField(
                        default="format-beige",
                        help_text="CSS class for card color (e.g., 'format-beige', 'format-light', 'format-teal')",
                        max_length=50,
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional link for the 'FIND OUT MORE' button",
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Business Service",
                "verbose_name_plural": "Business Services",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ServiceFeature",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                (
                    "icon_class",
                    models.CharField(
                        default="far fa-clock",
                        help_text="FontAwesome icon class (e.g., 'far fa-clock')",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="features",
                        to="main.businessservice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Feature",
                "verbose_name_plural": "Service Features",
                "ordering": ["order"],
            },
        ),
    ]
