# Generated by Django 5.2.1 on 2026-03-06 06:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0019_privacypolicy"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessservice",
            name="detailed_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True,
                help_text="Detailed description for the separate page",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="businessservice",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Image for the detailed page",
                null=True,
                upload_to="business_services/",
            ),
        ),
        migrations.AlterField(
            model_name="businessservice",
            name="color_class",
            field=models.CharField(
                help_text="CSS class for color, e.g., 'format-beige'", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="businessservice",
            name="icon_class",
            field=models.CharField(
                help_text="FontAwesome class, e.g., 'fas fa-book'", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="businessservice",
            name="link",
            field=models.CharField(
                blank=True,
                help_text="Optional external link",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="businessservice",
            name="order",
            field=models.IntegerField(default=0),
        ),
    ]
